### ISSUE TITLE
error: nix-shell requires a single derivation

### ISSUE THREAD

**Issue by wallacekelly-da** [obsidiansystems/nix-daml-sdk#9]
I am a nix-newbie. I was using the [Daml + Nix instructions](https://discuss.daml.com/t/daml-nix/7073?u=wallacekelly). I received an error that Google is not helping me resolve.

```
> git clone https://github.com/obsidiansystems/nix-daml-sdk.git
         :


> nix-shell --version
nix-shell (Nix) 2.22.1


> nix-shell ./nix-daml-sdk
error: nix-shell requires a single derivation
Try 'nix-shell --help' for more information.
```

This is on:

```
System Version: macOS 14.5 (23F79)
Kernel Version: Darwin 23.5.0
```

Any suggestions?

**Comment by alexfmpe** [comment]
`nix-shell` is a bit inconsistent in that it will default to `shell.nix` if you run it without args, but to `<folder>/default.nix` if you give it a file path. Try `cd nix-daml-sdk && nix-shell` or `nix-shell nix-daml-sdk/shell.nix`

**Comment by wallacekelly-da** [comment]
Thank you! That explained it.
